name: CI

on:
  push:
    branches: ["**"]
    tags: ["release-*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build Project
        run: bazel build //...

      - name: Run Tests
        run: bazel test //...

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login To ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Publish All Images
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/dev-')) ||
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/release-'))
        env:
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.ref_name }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: bazel run //:publish_images

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: infra/aws-minimal/package.json

      - name: Install AWS CDK app dependencies
        working-directory: infra/aws-minimal
        run: npm install

      - name: Deploy to AWS
        working-directory: infra/aws-minimal
        run: npx cdk synth && npx cdk deploy --require-approval never